set shell := ["nu", "-c"]

export RUST_LOG := "error"

@_default:
	just --list

build:
	cargo component build --quiet --manifest-path ./adder/Cargo.toml
	cargo component build --quiet --manifest-path ./calc/Cargo.toml
	wac plug \
		--output runnable.wasm \
		--plug ./adder/target/wasm32-wasip1/debug/add.wasm \
		./calc/target/wasm32-wasip1/debug/calc.wasm

clean:
	cargo clean --manifest-path ./adder/Cargo.toml
	cargo clean --manifest-path ./calc/Cargo.toml
	rm *.wasm

run:
	wasmtime ./runnable.wasm